lwotomd3 $HEADCFGFILE
lwotomd3 $UPPERCFGFILE
lwotomd3 $LOWERCFGFILE
cp head.md3 "F:\Games\Quake III Arena\BASEQ3\MODELS\PLAYERS\EYEGORE"
cp upper.md3 "F:\Games\Quake III Arena\BASEQ3\MODELS\PLAYERS\EYEGORE"
cp lower.md3 "F:\Games\Quake III Arena\BASEQ3\MODELS\PLAYERS\EYEGORE"


